services:
  db:
    image: mysql:9.3
    restart: always
    environment:
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'feedbacker'
    ports:
      - "3306:3306"
    volumes:
      - 'db:/var/lib/mysql'
    networks:
      - feedbacker_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9501:9501"
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    volumes:
      - ./backend:/opt/www
    networks:
      - feedbacker_network
    depends_on:
      - db

  frontend:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    networks:
      - feedbacker_network
    depends_on:
      - backend
      - db

volumes:
  db:
    driver: local

networks:
  feedbacker_network:
