services:
  db:
    image: mysql:9.3
    restart: always
    environment:
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'feedbacker'
    ports:
      - "3306:3306"
    volumes:
      - 'db:/var/lib/mysql'
    networks:
      - feedbacker_network

volumes:
  db:
    driver: local

networks:
  feedbacker_network:
